### ISSUE TITLE
Random crash  - 

### ISSUE THREAD

**Issue by lvnadrmwv** [GoVanguard/legion#207]
when adding new subnets to a an already saved project, scanning results in error below and forced to close container.

running in docker container, have rebuilt a few times. Able to reproduce by adding new subnets to an existing project.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/legion/app/importers/NmapImporter.py", line 102, in run
    db_host = self.hostRepository.getHostInformation(h.ip)
  File "/legion/db/repositories/HostRepository.py", line 50, in getHostInformation
    return session.query(hostObj).filter_by(ip=str(host_ip_address)).first()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3402, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3176, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: hostObj
[SQL: SELECT "hostObj".state AS "hostObj_state", "hostObj".count AS "hostObj_count", "hostObj".checked AS "hostObj_checked", "hostObj"."osMatch" AS "hostObj_osMatch", "hostObj"."osAccuracy" AS "hostObj_osAccuracy", "hostObj".vendor AS "hostObj_vendor", "hostObj".uptime AS "hostObj_uptime", "hostObj".lastboot AS "hostObj_lastboot", "hostObj".isp AS "hostObj_isp", "hostObj".asn AS "hostObj_asn", "hostObj".ip AS "hostObj_ip", "hostObj".ipv4 AS "hostObj_ipv4", "hostObj".ipv6 AS "hostObj_ipv6", "hostObj".macaddr AS "hostObj_macaddr", "hostObj".status AS "hostObj_status", "hostObj".hostname AS "hostObj_hostname", "hostObj"."hostId" AS "hostObj_hostId", "hostObj".id AS "hostObj_id", "hostObj".city AS "hostObj_city", "hostObj"."countryCode" AS "hostObj_countryCode", "hostObj"."postalCode" AS "hostObj_postalCode", "hostObj".longitude AS "hostObj_longitude", "hostObj".latitude AS "hostObj_latitude", "hostObj".distance AS "hostObj_distance" 
FROM "hostObj" 
WHERE "hostObj".ip = ?
 LIMIT ? OFFSET ?]
[parameters: ('10.1.15.65', 1, 0)]

**Comment by lvnadrmwv** [comment]
also, when pulling open a saved session, all of the references in "tool" are blank hosts and services are there , but tool reults are blank.

**Comment by lvnadrmwv** [comment]
last error:

{"time": "2022-01-19 21:16:16,428", "name": "Failed to sort", "level": "ERROR", "data": {"logger_name": "legion"}, "context": {"module": "processmodels", "filename": "processmodels.py", "line": 136}}

**Comment by lvnadrmwv** [comment]
current situation is that wether run from docker or run with latest NON docker and python 3.9.9, I will get random points during a scan where it will error with error below. Unfortunately when re-loading and opening saved session I then get the sort error above and nothing works. have no choice but to start new project.

have rebooted and rebuilt the docker container as well as removed and reinstalled non-docker via apt. Also cloned the non-docker beta to try it. cant seem to have a project stay current or not to crash. All other tools on the box seem to be working OK.





{"time": "2022-01-20 16:40:54,919", "name": "Process 3 is done!", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "controller", "filename": "controller.py", "line": 839}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: hostObj

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/legion/app/importers/NmapImporter.py", line 102, in run
    db_host = self.hostRepository.getHostInformation(h.ip)
  File "/legion/db/repositories/HostRepository.py", line 50, in getHostInformation
    return session.query(hostObj).filter_by(ip=str(host_ip_address)).first()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3402, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3176, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: hostObj
[SQL: SELECT "hostObj".state AS "hostObj_state", "hostObj".count AS "hostObj_count", "hostObj".checked AS "hostObj_checked", "hostObj"."osMatch" AS "hostObj_osMatch", "hostObj"."osAccuracy" AS "hostObj_osAccuracy", "hostObj".vendor AS "hostObj_vendor", "hostObj".uptime AS "hostObj_uptime", "hostObj".lastboot AS "hostObj_lastboot", "hostObj".isp AS "hostObj_isp", "hostObj".asn AS "hostObj_asn", "hostObj".ip AS "hostObj_ip", "hostObj".ipv4 AS "hostObj_ipv4", "hostObj".ipv6 AS "hostObj_ipv6", "hostObj".macaddr AS "hostObj_macaddr", "hostObj".status AS "hostObj_status", "hostObj".hostname AS "hostObj_hostname", "hostObj"."hostId" AS "hostObj_hostId", "hostObj".id AS "hostObj_id", "hostObj".city AS "hostObj_city", "hostObj"."countryCode" AS "hostObj_countryCode", "hostObj"."postalCode" AS "hostObj_postalCode", "hostObj".longitude AS "hostObj_longitude", "hostObj".latitude AS "hostObj_latitude", "hostObj".distance AS "hostObj_distance" 
FROM "hostObj" 
WHERE "hostObj".ip = ?
 LIMIT ? OFFSET ?]
[parameters: ('10.1.2.1', 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by sscottgvit** [comment]
This is indeed a common problem in older versions of legion. The recent updates not only should dramatically improve performance but reduce the chance of this type of transaction problem occurring to rare at best.
