### ISSUE TITLE
Legion crashes when adding a new scope

### ISSUE THREAD

**Issue by Jerin-004** [GoVanguard/legion#228]
Did not find service *********** name=http-proxy prod=Apache Traffic Server ver= extra= fing=
Traceback (most recent call last):
  File "/usr/share/legion/app/importers/NmapImporter.py", line 184, in run
    self.updateProgressObservable.updateProgress(totalprogress)
  File "/usr/share/legion/app/actions/updateProgress/UpdateProgressObservable.py", line 32, in updateProgress
    observer.onProgressUpdate(progress)
  File "/usr/share/legion/ui/observers/QtUpdateProgressObserver.py", line 33, in onProgressUpdate
    self.progressWidget.setProgress(progress)
  File "/usr/share/legion/ui/ancillaryDialog.py", line 55, in setProgress
    self.progressBar.setValue(progress)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
zsh: IOT instruction  legion

**Comment by dcarlsongvit** [comment]
This issue should be resolved.
