### ISSUE TITLE
Legion crashes: "TypeError"

### ISSUE THREAD

**Issue by Hanselaffe** [GoVanguard/legion#260]
Legion crashes with the messages "MissingData" inside the GUI. 
Inside the console it gives my an TypeError

[05:44:29 AM] INFO     Creating temporary project at application start...                                                                      legion.py:145
              INFO     Established SQLite connection on file '/root/.local/share/legion/tmp/legion-d_udns1c.legion'                    SqliteDbAdapter.py:58
              INFO     Wordlist was created/opened: /root/.local/share/legion/tmp/legion-vl1zcioi-tool-output/legion-usernames.txt          auxiliary.py:186
              INFO     Wordlist was created/opened: /root/.local/share/legion/tmp/legion-vl1zcioi-tool-output/legion-passwords.txt          auxiliary.py:186
[05:44:30 AM] INFO     Loading settings file..                                                                                                settings.py:37
              INFO     Legion started successfully.                                                                                            legion.py:165
[05:44:40 AM] INFO     runStagedNmap called for stage 1                                                                                    controller.py:773
              INFO     Adding process: <db.entities.process.process object at 0x7f8f1edf34a0>                                        ProcessRepository.py:69
              INFO     Queuing: nmap -T4 -sV -sSU -O -p T:80,81,443,4443,8080,8081,8082 -vvvv 10.10.10.10 -oA                              controller.py:704
                       /root/.local/share/legion/tmp/legion-jx9w4uh6-running/nmap/20241007054440911395-nmapstage1                                           
              INFO     Running: nmap -T4 -sV -sSU -O -p T:80,81,443,4443,8080,8081,8082 -vvvv 10.10.10.10 -oA                              controller.py:624
                       /root/.local/share/legion/tmp/legion-jx9w4uh6-running/nmap/20241007054440911395-nmapstage1                                           
              INFO     runCommand called for stage 1                                                                                       controller.py:724
              INFO     runCommand connected for stage 1                                                                                    controller.py:727
Warning: program compiled against libxml 212 using older 209
[05:44:43 AM] INFO     Process 1 is done!                                                                                                  controller.py:882
QBasicTimer::stop: Failed. Possibly trying to stop from a different thread
              INFO     Storing process output into db: <db.entities.processOutput.process_output object at 0x7f8f1c536f30>           ProcessRepository.py:86
              INFO     Halting process panel update timer as all processes are finished.                                                   controller.py:639
              INFO     runStagedNmap called for stage 2                                                                                    controller.py:773
              INFO     Adding process: <db.entities.process.process object at 0x7f8f1c55ac00>                                        ProcessRepository.py:69
              INFO     Queuing: nmap -T4 -sV -sSU -O -p T:25,135,137,139,445,1433,3306,5432,U:137,161,162,1434 -vvvv 10.10.10.10 -oA       controller.py:704
                       /root/.local/share/legion/tmp/legion-jx9w4uh6-running/nmap/20241007054443219415-nmapstage2                                           
              INFO     Running: nmap -T4 -sV -sSU -O -p T:25,135,137,139,445,1433,3306,5432,U:137,161,162,1434 -vvvv 10.10.10.10 -oA       controller.py:624
                       /root/.local/share/legion/tmp/legion-jx9w4uh6-running/nmap/20241007054443219415-nmapstage2                                           
              INFO     runCommand called for stage 2                                                                                       controller.py:724
              INFO     runCommand connected for stage 2                                                                                    controller.py:727
              INFO     Scheduler started!                                                                                                  controller.py:914
              INFO     -----------------------------------------------                                                                     controller.py:923
              INFO     Scheduler ended!                                                                                                    controller.py:924
Warning: program compiled against libxml 212 using older 209
[05:44:45 AM] INFO     Process 2 is done!                                                                                                  controller.py:882
              INFO     Storing process output into db: <db.entities.processOutput.process_output object at 0x7f8f1c5bcf50>           ProcessRepository.py:86
              INFO     Halting process panel update timer as all processes are finished.                                                   controller.py:639
              INFO     runStagedNmap called for stage 3                                                                                    controller.py:773
              INFO     Adding process: <db.entities.process.process object at 0x7f8f1c592f30>                                        ProcessRepository.py:69
              INFO     Queuing: nmap -sV --script=vulners -vvvv 10.10.10.10 -oA                                                            controller.py:704
                       /root/.local/share/legion/tmp/legion-jx9w4uh6-running/nmap/20241007054445522210-nmapstage3                                           
              INFO     Running: nmap -sV --script=vulners -vvvv 10.10.10.10 -oA                                                            controller.py:624
                       /root/.local/share/legion/tmp/legion-jx9w4uh6-running/nmap/20241007054445522210-nmapstage3                                           
              INFO     runCommand called for stage 3                                                                                       controller.py:724
              INFO     runCommand connected for stage 3                                                                                    controller.py:727
              INFO     Scheduler started!                                                                                                  controller.py:914
              INFO     -----------------------------------------------                                                                     controller.py:923
              INFO     Scheduler ended!                                                                                                    controller.py:924
**Traceback (most recent call last):
  File "/usr/share/legion/ui/view.py", line 1005, in contextMenuProcessesTableView
    selectedProcesses.append([int(pid), self.ProcessesTableModel.getProcessStatusForRow(row.row()),
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/legion/ui/models/processmodels.py", line 160, in getProcessStatusForRow
    return self.__processes[row]['status']
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 54, in sqlalchemy.cyextension.resultproxy.BaseRow.__getitem__
TypeError: tuple indices must be integers or slices, not str
Aborted**

**Comment by Picachu5137** [comment]
same error after upgrade packages, try rollback to earlier version

**Comment by Hanselaffe** [comment]
> same error after upgrade packages, try rollback to earlier version

thanks for the advice. You mean earlier version of legion or my kali?

**Comment by sscottgvit** [comment]
I do have a solution for this that will be coming in the first release on the new repo very soon.

**Comment by mmmmcoffee** [comment]
> I do have a solution for this that will be coming in the first release on the new repo very soon.

Can you give a quick pseudo description of the changes if they're small enough? Running into this with a current project and cant track down the solution
