### ISSUE TITLE
add it to scope and continue. Will crash

### ISSUE THREAD

**Issue by CoffeeorteaH** [GoVanguard/legion#88]
```
Traceback (most recent call last):
  File "/opt/legion/ui/view.py", line 1419, in <lambda>
    bWidget.runButton.clicked.connect(lambda: self.callHydra(bWidget))
  File "/opt/legion/ui/view.py", line 1469, in callHydra
    self.controller.addHosts(str(bWidget.ipTextinput.text()).replace(';',' '), False, False)
  File "/opt/legion/app/auxiliary.py", line 40, in wrap
    result = f(*args, **kw)
TypeError: addHosts() missing 2 required positional arguments: 'nmapSpeed' and 'scanMode'
./startLegion.sh：行 30: 94809 core dumped               ${PYTHON3BIN} legion.py
```

**Comment by sscottgvit** [comment]
What version of Linux and Python are you running?

**Comment by CoffeeorteaH** [comment]
Sorry, I forgot to mention this information.

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/19629138/55671606-5be3c980-58c4-11e9-9ba7-d3ee0526a829.png">

```
root@kali:/opt/legion# ./startLegion.sh 
Strap yourself in, we're starting Legion...
Python 3 bin is python3 (/usr/bin/python3)
Pip 3 bin is pip3 (/usr/bin/pip3)
Detected Kali 2019 
 __       _______   _______  __    ______   .__   __. 
|  |     |   ____| /  _____||  |  /  __  \  |  \ |  | 
|  |     |  |__   |  |  __  |  | |  |  |  | |   \|  | 
|  |     |   __|  |  | |_ | |  | |  |  |  | |  . `  | 
|  `----.|  |____ |  |__| | |  | |  `--'  | |  |\   | 
|_______||_______| \______| |__|  \______/  |__| \__| 
                                                      

{"time": "2019-04-06 23:29:59,762", "name": "Creating temporary files..", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "logic", "filename": "logic.py", "line": 30}}
{"time": "2019-04-06 23:29:59,770", "name": "/opt/legion/", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "logic", "filename": "logic.py", "line": 32}}
{"time": "2019-04-06 23:29:59,774", "name": "Wordlist was created/opened: ./tmp/legion-tlecvkml-tool-output/legion-usernames.txt", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "auxiliary", "filename": "auxiliary.py", "line": 185}}
{"time": "2019-04-06 23:29:59,775", "name": "Wordlist was created/opened: ./tmp/legion-tlecvkml-tool-output/legion-passwords.txt", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "auxiliary", "filename": "auxiliary.py", "line": 185}}
{"time": "2019-04-06 23:29:59,775", "name": "/opt/legion/tmp/legion-kho65c2t.legion", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "logic", "filename": "logic.py", "line": 42}}
{"time": "2019-04-06 23:30:02,921", "name": "Loading settings file..", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "settings", "filename": "settings.py", "line": 26}}
{"time": "2019-04-06 23:30:10,244", "name": "Adding host to scope here!!", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "view", "filename": "view.py", "line": 1468}}
Traceback (most recent call last):
  File "/opt/legion/ui/view.py", line 1419, in <lambda>
    bWidget.runButton.clicked.connect(lambda: self.callHydra(bWidget))
  File "/opt/legion/ui/view.py", line 1469, in callHydra
    self.controller.addHosts(str(bWidget.ipTextinput.text()).replace(';',' '), False, False)
  File "/opt/legion/app/auxiliary.py", line 40, in wrap
    result = f(*args, **kw)
TypeError: addHosts() missing 2 required positional arguments: 'nmapSpeed' and 'scanMode'
./startLegion.sh：行 30: 107878                ${PYTHON3BIN} legion.py
```

Any unscanned IP, as long as I work directly with brute. Click Yes to crash directly.

```
root@kali:/opt/legion# uname -a
Linux kali 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux

root@kali:/opt/legion# python3 --version
Python 3.7.2+
```

**Comment by jchoy14** [comment]
Thank you, this should be working in the current development branch now and the fix will be included in the next update.
